#!/usr/bin/env python3
"""Text style check for tracked repository files (see docs/STYLE.md).

Rules, in the order they are reported:

1. PICTOGRAPH  No emoji or pictograph characters (including variation selectors
               and joiners) in any tracked text file.
2. CJK         No CJK characters (they appear by accident in generated text).
3. DASH        No em dash or en dash in code, configuration and scripts. Prose
               documents (.md, .tex, .txt) may use them. A few lines of Polish
               product content in code are allowed (PRODUCT_DASH_LINES below).
4. POLISH      Polish letters only where Polish is intended: product content
               and historical documents (POLISH_ALLOWED_PATHS), or inside a
               quoted string / code span anywhere else (for example a README
               sentence that quotes a UI message). Prose must be English.

Run from the repository root:   python3 scripts/check-text-style.py
Exit status: 0 = clean, 1 = violations (each is printed as path:line: RULE text).
Pure standard library; it reads only files that git tracks.
"""

import argparse
import re
import subprocess
import sys
from pathlib import Path

# The character classes are written as escapes so that this file passes its own check.
PICTOGRAPH = re.compile("[\U0001F000-\U0001FAFF\u2600-\u27bf\u2b00-\u2bff\ufe0f\u200d]")
CJK = re.compile("[\u2e80-\u2fdf\u3000-\u9fff\uf900-\ufaff\uff01-\uff5e]")
POLISH = re.compile("[\u0105\u0107\u0119\u0142\u0144\u00f3\u015b\u017a\u017c\u0104\u0106\u0118\u0141\u0143\u00d3\u015a\u0179\u017b]")
DASH = re.compile("[\u2013\u2014]")

BINARY_SUFFIXES = (".png", ".jpg", ".jpeg", ".gif", ".pdf", ".docx", ".xlsx", ".zip", ".gz", ".ico", ".woff", ".woff2")
PROSE_SUFFIXES = (".md", ".tex", ".txt")

# Polish is product content or a historical record here (owner decision, 2026-10-09).
POLISH_ALLOWED_PATHS = (
    "docs/history/",  # historical review and audit documents stay Polish
    "docker/viewer/",  # the two UI pages, their Playwright tests and snapshots
    "docker/grading-api/app/db.py",  # Lung-RADS labels and placeholder reports (radiologist's spec)
    "docker/viewer/tests/",
)
# Lines of Polish product text that legitimately contain a dash inside code.
PRODUCT_DASH_LINES = (
    re.compile(r'"Kategoria \w+ [\u2013\u2014] '),
    re.compile(r'"PLACEHOLDER \u2014 nie jest to prawdziwy opis kliniczny'),
    re.compile(r"Tw\u00f3j post\u0119p si\u0119 zmieni\u0142 \u2014"),
)
_QUOTED = re.compile(r'"[^"\n]*"|\u201e[^\u201d\n]*\u201d|`[^`\n]*`|\'[^\'\n]*\'')


def tracked_files(root: Path):
    out = subprocess.run(["git", "-C", str(root), "ls-files", "-z"], capture_output=True, check=True).stdout
    for raw in out.split(b"\0"):
        name = raw.decode("utf-8", "replace")
        if name and not name.endswith(BINARY_SUFFIXES):
            yield name


def _outside_quotes(line: str, inside: bool):
    """Return (text outside quoted strings, still-inside-a-double-quote-at-end-of-line).

    A UI message quoted in prose often wraps across a line break, so an unclosed
    double quote carries over to the next line."""
    kept, i = [], 0
    if inside:
        j = line.find('"')
        if j < 0:
            return "", True
        i, inside = j + 1, False
    rest = _QUOTED.sub("", line[i:])
    k = rest.find('"')
    if k >= 0:  # an opening quote with no closing one on this line
        return "".join(kept) + rest[:k], True
    return rest, False


def check_file(rel: str, text: str):
    prose = rel.endswith(PROSE_SUFFIXES)
    polish_ok = rel.startswith(POLISH_ALLOWED_PATHS) or rel in POLISH_ALLOWED_PATHS
    inside = False
    for n, line in enumerate(text.split("\n"), 1):
        # A quote may wrap across lines only within one Markdown paragraph; in code
        # files unbalanced quote characters are common, so the state never carries over.
        if not rel.endswith(".md") or not line.strip():
            inside = False
        outside, inside = _outside_quotes(line, inside)
        if PICTOGRAPH.search(line):
            yield n, "PICTOGRAPH", "emoji or pictograph character"
        if CJK.search(line):
            yield n, "CJK", "CJK character (probably generated by accident)"
        if not prose and DASH.search(line) and not any(p.search(line) for p in PRODUCT_DASH_LINES):
            yield n, "DASH", "em/en dash in code or configuration (use an ASCII hyphen)"
        if not polish_ok and POLISH.search(outside):
            yield n, "POLISH", "Polish letters outside a quoted string (write documentation in English)"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--root", default=".", help="repository root (default: current directory)")
    a = ap.parse_args(argv)
    root = Path(a.root)
    problems = 0
    for rel in tracked_files(root):
        try:
            text = (root / rel).read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue
        for n, rule, msg in check_file(rel, text):
            print(f"{rel}:{n}: {rule} {msg}")
            problems += 1
    if problems:
        print(f"\n{problems} text style violation(s); see docs/STYLE.md", file=sys.stderr)
        return 1
    print("text style check passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
